---
apiVersion: v1
kind: Service
metadata:
  name: spark-ui-service
  namespace: spark-streaming
spec:
  selector:
    app: pyspark
  ports:
    - protocol: TCP
      port: 4040
      targetPort: 4040
      nodePort: 30040  # Fixed NodePort
  type: NodePort

